### ISSUE TITLE
Maintainer and Ownership

### ISSUE THREAD

**Issue by d0nutptr** [chenhengqi/libxdp-sys#3]
Hello!

I see this crate hasn’t been updated in 7 months and the crate is missing key functions (see #2 ). I wanted to reach out and see if you would be open to adding an additional maintainer so I could publish updates to `libxdp-sys` on crates.io .

I managed to figure out how to address #2 and have an interest in maintaining `libxdp-sys` so I can move away from pre-1.0 `libbpf-sys` for my projects.

Thank you! Also, after some clean up, I’ll submit a PR to resolve #2 later today.

**Comment by chenhengqi** [comment]
@d0nutptr Just send you an invitation.

**Comment by d0nutptr** [comment]
Thanks! Let me get that PR up :) 

I'll close this ticket out since it's resolved
